2021-06-15 00:27:27 database: close
org.h2.message.DbException: File corrupted while reading record: "wrong checksum". Possible solution: use the recovery tool [90030-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.pagestore.PageStore.getPage(PageStore.java:752)
	at org.h2.pagestore.PageStore.compact(PageStore.java:706)
	at org.h2.pagestore.PageStore.compact(PageStore.java:534)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1517)
	at org.h2.engine.Database.closeImpl(Database.java:1454)
	at org.h2.engine.Database.close(Database.java:1373)
	at org.h2.engine.Database.removeSession(Database.java:1307)
	at org.h2.engine.Session.close(Session.java:963)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:453)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:103)
	at org.flywaydb.core.internal.database.base.Connection.close(Connection.java:115)
	at org.flywaydb.core.internal.database.base.Database.close(Database.java:367)
	at org.flywaydb.core.internal.util.IOUtils.close(IOUtils.java:37)
	at org.flywaydb.core.Flyway.execute(Flyway.java:577)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:119)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:111)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:105)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:54)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:37)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:44)
	at scala.meta.internal.metals.Tables.$anonfun$buildServers$1(Tables.scala:31)
	at scala.meta.internal.metals.ChosenBuildServers.selectedServer(ChosenBuildServers.scala:12)
	at scala.meta.internal.metals.MetalsLanguageServer.updateWorkspaceDirectory(MetalsLanguageServer.scala:349)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$initialize$2(MetalsLanguageServer.scala:741)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: "wrong checksum". Possible solution: use the recovery tool [90030-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 37 more
2021-07-06 15:09:57 database: close
org.h2.message.DbException: File corrupted while reading record: "wrong checksum". Possible solution: use the recovery tool [90030-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.pagestore.PageStore.getPage(PageStore.java:752)
	at org.h2.pagestore.PageStore.compact(PageStore.java:706)
	at org.h2.pagestore.PageStore.compact(PageStore.java:534)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1517)
	at org.h2.engine.Database.closeImpl(Database.java:1454)
	at org.h2.engine.Database.close(Database.java:1373)
	at org.h2.engine.Database.removeSession(Database.java:1307)
	at org.h2.engine.Session.close(Session.java:963)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:453)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:103)
	at org.flywaydb.core.internal.database.base.Connection.close(Connection.java:115)
	at org.flywaydb.core.internal.database.base.Database.close(Database.java:367)
	at org.flywaydb.core.internal.util.IOUtils.close(IOUtils.java:37)
	at org.flywaydb.core.Flyway.execute(Flyway.java:577)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at scala.meta.internal.metals.Tables.migrateOrRestart(Tables.scala:119)
	at scala.meta.internal.metals.Tables.tryUrl(Tables.scala:111)
	at scala.meta.internal.metals.Tables.persistentConnection(Tables.scala:105)
	at scala.meta.internal.metals.Tables.tryAutoServer(Tables.scala:54)
	at scala.meta.internal.metals.Tables.connect(Tables.scala:37)
	at scala.meta.internal.metals.Tables.connection(Tables.scala:44)
	at scala.meta.internal.metals.Tables.$anonfun$buildServers$1(Tables.scala:31)
	at scala.meta.internal.metals.ChosenBuildServers.selectedServer(ChosenBuildServers.scala:12)
	at scala.meta.internal.metals.MetalsLanguageServer.updateWorkspaceDirectory(MetalsLanguageServer.scala:349)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$initialize$2(MetalsLanguageServer.scala:741)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: "wrong checksum". Possible solution: use the recovery tool [90030-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 37 more
